language: php

php:
  - 5.3
  - 5.4
  - 5.5

services:
  - mongodb

before_script:
  - pecl install xhprof-beta
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = xhprof.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
  - composer install --prefer-dist --dev
  - chmod -R 0777 cache/

script: phpunit
